tap "coursier/formulas"
tap "dagger/tap"
tap "dbcli/tap"
tap "eth-p/software"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazygit"
tap "withgraphite/tap"
# Run your GitHub Actions locally 🚀
brew "act"
# Core application library for C
brew "glib"
# OpenType text shaping engine
brew "harfbuzz"
# Ammonite is a cleanroom re-implementation of the Scala REPL
brew "ammonite-repl"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Official Amazon AWS command-line interface
brew "awscli"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Configurable talking characters in ASCII art
brew "cowsay"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Secure runtime for JavaScript and TypeScript
brew "deno"
# Modern replacement for 'ls'
brew "exa"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Collection of GNU find, xargs, and locate
brew "findutils"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Fast and simple Node.js version manager
brew "fnm"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU compiler collection
brew "gcc"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Render markdown on the CLI
brew "glow"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Command-driven, interactive function plotting
brew "gnuplot"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# GNU grep, egrep and fgrep
brew "grep"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Add GitHub support to git on the command-line
brew "hub"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Lazier way to manage everything docker
brew "lazydocker"
# Pager program similar to more
brew "less"
# Rainbows and unicorns in your console!
brew "lolcat"
# Mac App Store command-line interface
brew "mas"
# Show markdown documents on text terminals
brew "mdcat"
# Scala build tool
brew "mill"
# Collection of tools that nobody wrote when UNIX was young
brew "moreutils"
# Open source relational database management system
brew "mysql"
# Free (GNU) replacement for the Pico text editor
brew "nano"
# Modern shell for the GitHub era
brew "nushell"
# OpenBSD freely-licensed SSH connectivity tools
brew "openssh"
# Swiss-army knife of markup format conversion
brew "pandoc"
# CLI for Postgres with auto-completion and syntax highlighting
brew "pgcli"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# 📦🚀 Fast, disk space efficient package manager
brew "pnpm"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# CLI for managing and maintaining data graphs with Apollo Studio
brew "rover"
# Rust toolchain installer
brew "rustup-init"
# Terminal multiplexer with VT100/ANSI terminal emulation
brew "screen"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Cross-shell prompt for astronauts
brew "starship"
# Traceroute implementation using TCP packets
brew "tcptraceroute"
# Programmatically correct mistyped console commands
brew "thefuck"
# Simplified and community-driven man pages
brew "tldr"
# Tool for writing command-line pipes with instant live preview
brew "up"
# Vi 'workalike' with many additional features
brew "vim"
# Internet file retriever
brew "wget"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Launcher for Coursier
brew "coursier/formulas/coursier"
# Dagger is a programmable deployment system.
brew "dagger/tap/dagger"
# Bash scripts that integrate bat with various command-line tools
brew "eth-p/software/bat-extras"
# A simple terminal UI for git commands, written in Go
brew "jesseduffield/lazygit/lazygit"
# The Graphite CLI allows you to easily manage your stacked-diff workflow.
brew "withgraphite/tap/graphite"
# Password manager that keeps all passwords secure behind one password
cask "1password-beta"
# Application launcher and productivity software
cask "alfred"
# Inspect application bundles
cask "apparency"
# Application uninstaller
cask "appcleaner"
# Web browser focusing on privacy
cask "brave-browser-dev"
# E-books management software
cask "calibre"
# Free and open-source web browser
cask "chromium"
# API documentation browser and code snippet manager
cask "dash"
# Voice and text chat software
cask "discord"
# App to build and share containerized applications and microservices
cask "docker"
# Client for the Dropbox cloud storage service
cask "dropbox-beta"
# Collaborative meeting agendas, notes, and action items
cask "fellow"
# Collaborative team software
cask "figma-beta"
# Web browser
cask "firefox-developer-edition"
# Developer targeted fonts with a high number of glyphs
cask "font-fira-code-nerd-font"
# Developer targeted fonts with a high number of glyphs
cask "font-jetbrains-mono-nerd-font"
# Developer targeted fonts with a high number of glyphs
cask "font-victor-mono-nerd-font"
# Desktop client for GitHub repositories
cask "github-beta"
# Web browser
cask "google-chrome"
# Tools to protect your files
cask "gpg-suite-no-mail"
# Utility to fix grammar errors and style issues in text
cask "grammarly"
# GraphQL IDE for better development workflows
cask "graphql-playground"
# Access the HEY email service
cask "hey"
# JetBrains tools manager
cask "jetbrains-toolbox"
# End-to-end encryption software
cask "keybase"
# App to manage software development and track bugs
cask "linear-linear"
# Online collaborative whiteboard platform
cask "miro"
# Visual tool to design, develop and administer MySQL servers
cask "mysqlworkbench"
# App to write, plan, collaborate, and get organized
cask "notion"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Scheduling application focusing on organization
cask "omnifocus"
# QuickLook plug-in that renders source code with syntax highlighting
cask "qlcolorcode"
# Display image info and preview unsupported formats in QuickLook
cask "qlimagesize"
# QuickLook generator for Markdown files
cask "qlmarkdown"
# QuickLook plugin for plaintext files without an extension
cask "qlstephen"
# Thumbnails, static previews, cover art and metadata for video files
cask "qlvideo"
# QuickLook plugin for JSON files
cask "quicklook-json"
# QuickLook generator for Adobe Swatch Exchange files
cask "quicklookase"
# All-in-one bookmark manager
cask "raindropio"
# Control your tools with a few keystrokes
cask "raycast"
# Team communication and collaboration software
cask "slack-beta"
# Native GUI tool for relational databases
cask "tableplus"
# Open-source BitTorrent client
cask "transmission"
# Configurable document editor that supports Markdown
cask "typora"
# Code editor
cask "visual-studio-code-insiders"
# Desktop client for WhatsApp
cask "whatsapp"
# Video communication and virtual meeting platform
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "Boop", id: 1518425043
mas "Bumpr", id: 1166066070
mas "Developer", id: 640199958
mas "FileBot", id: 905384638
mas "Grammarly for Safari", id: 1462114288
mas "Magnet", id: 441258766
mas "Playgrounds", id: 1496833156
mas "Save to Raindrop.io", id: 1549370672
mas "Twitter", id: 1482454543
mas "Wipr", id: 1320666476
mas "Xcode", id: 497799835
