tap "eth-p/software"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "jesseduffield/lazygit"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Official Amazon AWS command-line interface
brew "awscli"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Core application library for C
brew "glib"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Configurable talking characters in ASCII art
brew "cowsay"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Secure runtime for JavaScript and TypeScript
brew "deno", link: false
# Modern replacement for 'ls'
brew "exa"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Collection of GNU find, xargs, and locate
brew "findutils"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU compiler collection
brew "gcc"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Extensions to follow Vincent Driessen's branching model
brew "git-flow"
# Trim your git remote tracking branches that are merged or gone
brew "git-trim"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# GNU grep, egrep and fgrep
brew "grep"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Add GitHub support to git on the command-line
brew "hub"
# Pager program similar to more
brew "less"
# Rainbows and unicorns in your console!
brew "lolcat"
# Mac App Store command-line interface
brew "mas"
# Show markdown documents on text terminals
brew "mdcat"
# Collection of tools that nobody wrote when UNIX was young
brew "moreutils"
# Free (GNU) replacement for the Pico text editor
brew "nano"
# Modern shell for the GitHub era
brew "nushell"
# Manage multiple Node.js versions
brew "nvm"
# OpenBSD freely-licensed SSH connectivity tools
brew "openssh"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Rust toolchain installer
brew "rustup-init"
# Terminal multiplexer with VT100/ANSI terminal emulation
brew "screen"
# Cross-shell prompt for astronauts
brew "starship"
# Tool to build, change, and version infrastructure
brew "terraform"
# Programmatically correct mistyped console commands
brew "thefuck"
# Simplified and community-driven man pages
brew "tldr", link: false
# Language for application scale JavaScript development
brew "typescript"
# Vi 'workalike' with many additional features
brew "vim"
# JavaScript toolchain manager for reproducible environments
brew "volta"
# Watch files and take action when they change
brew "watchman"
# Internet file retriever
brew "wget"
# JavaScript package manager
brew "yarn"
# Bash scripts that integrate bat with various command-line tools
brew "eth-p/software/bat-extras"
# A simple terminal UI for git commands, written in Go
brew "jesseduffield/lazygit/lazygit"
# Command-line helper for the 1Password password manager
cask "1password-cli"
# GPU-accelerated terminal emulator
cask "alacritty"
# Application launcher and productivity software
cask "alfred"
# Inspect application bundles
cask "apparency"
# Application uninstaller
cask "appcleaner"
# E-books management software
cask "calibre"
# App to build and share containerized applications and microservices
cask "docker"
# Web browser
cask "firefox-developer-edition"
cask "font-fira-code-nerd-font"
cask "font-victor-mono-nerd-font"
# Git client focusing on productivity
cask "gitkraken"
# Web browser
cask "google-chrome"
# Access the HEY email service
cask "hey"
# IDE for Java development - community edition
cask "intellij-idea-ce"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2-beta"
cask "microsoft-teams"
cask "miro"
# VPN client for secure internet access and private browsing
cask "nordvpn"
# App to write, plan, collaborate, and get organized
cask "notion"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
cask "paletro"
# QuickLook plug-in that renders source code with syntax highlighting
cask "qlcolorcode"
# Display image info and preview unsupported formats in QuickLook
cask "qlimagesize"
# QuickLook generator for Markdown files
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
# Web browser
cask "safari-technology-preview"
# Team communication and collaboration software
cask "slack-beta"
# Music streaming service
cask "spotify"
# Application for inspecting installer packages
cask "suspicious-package"
# Open-source BitTorrent client
cask "transmission"
# Free and open-source OpenVPN client
cask "tunnelblick"
# Configurable document editor that supports Markdown
cask "typora"
# Code editor
cask "visual-studio-code-insiders"
# Desktop client for WhatsApp
cask "whatsapp"
# Video communication and virtual meeting platform
cask "zoom"
mas "Boop", id: 1518425043
mas "Bumpr", id: 1166066070
mas "FileBot", id: 905384638
mas "Ghostery Lite", id: 1436953057
mas "Grammarly for Safari", id: 1462114288
mas "Jira", id: 1475897096
mas "Kindle", id: 405399194
mas "Magnet", id: 441258766
mas "NordVPN IKE", id: 1116599239
mas "Save to Raindrop.io", id: 1549370672
mas "Twitter", id: 1482454543
