tap "dbcli/tap"
tap "eth-p/software"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "jesseduffield/lazygit"
brew "python@3.9"
brew "awscli"
brew "bash"
brew "bat"
brew "coreutils"
brew "cowsay"
brew "curl"
brew "deno"
brew "direnv"
brew "exa"
brew "fd"
brew "findutils"
brew "fish"
brew "fzf"
brew "gcc"
brew "gh"
brew "git"
brew "git-delta"
brew "git-flow"
brew "glib"
brew "go"
brew "grep"
brew "httpie"
brew "hub"
brew "jq"
brew "less"
brew "lolcat"
brew "mas"
brew "mdcat"
brew "moreutils"
brew "nano"
brew "nushell"
brew "nvm"
brew "openssh"
brew "pandoc"
brew "pgcli"
brew "ripgrep"
brew "rustup-init"
brew "screen"
brew "shellcheck"
brew "starship"
brew "subversion"
brew "tcptraceroute"
brew "thefuck"
brew "tldr"
brew "typescript"
brew "up"
brew "vim"
brew "watchman"
brew "wget"
brew "yarn"
brew "zoxide"
brew "eth-p/software/bat-extras"
brew "jesseduffield/lazygit/lazygit"
cask "1password-cli"
cask "alfred"
cask "apparency"
cask "appcleaner"
cask "calibre"
cask "docker"
cask "drawio"
cask "dropbox-beta"
cask "firefox-developer-edition"
cask "font-fira-code-nerd-font"
cask "font-victor-mono-nerd-font"
cask "google-chrome-dev"
cask "hey"
cask "iterm2-beta"
cask "miro"
cask "nordvpn"
cask "notion"
cask "obsidian"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "raindropio"
cask "slack-beta"
cask "spotify"
cask "studio-3t"
cask "transmission"
cask "tunnelblick"
cask "typora"
cask "visual-studio-code-insiders"
cask "whatsapp"
cask "zoom"
mas "1Password 7", id: 1333542190
mas "Boop", id: 1518425043
mas "Bumpr", id: 1166066070
mas "Developer", id: 640199958
mas "FileBot", id: 905384638
mas "Ghostery Lite", id: 1436953057
mas "GoodNotes", id: 1444383602
mas "Grammarly for Safari", id: 1462114288
mas "Jira", id: 1475897096
mas "Kindle", id: 405399194
mas "Magnet", id: 441258766
mas "NordVPN IKE", id: 1116599239
mas "Save to Raindrop.io", id: 1549370672
mas "Twitter", id: 1482454543
