# Homebrew Configuration
# This module manages Homebrew taps, formulae, casks, and Mac App Store apps
{hostConfig, ...}: {
  homebrew = {
    enable = true; # Whether to enable nix-darwin to manage installing/updating/upgrading Homebrew taps, formulae, and casks, as well as Mac App Store apps and Docker containers, using Homebrew Bundle.

    global = {
      autoUpdate = true; # Whether to enable Homebrew to auto-update itself and all formulae when you manually invoke commands like brew install, brew upgrade, brew tap, and brew bundle [install].
      brewfile = false; # Whether to enable Homebrew to automatically use the Brewfile that this module generates in the Nix store, when you manually invoke brew bundle.
    };

    caskArgs = {
      appdir = "/Applications"; # Target Cask location for Applications.
      colorpickerdir = "~/Library/ColorPickers"; # Target location for Color Pickers.
      prefpanedir = "~/Library/PreferencePanes"; # Target location for Preference Panes.
      qlplugindir = "~/Library/QuickLook"; # Target location for QuickLook Plugins.
      mdimporterdir = "~/Library/Spotlight"; # Target location for Spotlight Plugins.
      dictionarydir = "~/Library/Dictionaries"; # Target location for Dictionaries.
      fontdir = "~/Library/Fonts"; # ~/Library/Fonts
      servicedir = "~/Library/Services"; # Target location for Services.
      input_methoddir = "~/Library/Input Methods"; # Target location for Input Methods.
      internet_plugindir = "~/Library/Internet Plug-Ins"; # Target location for Internet Plugins.
      audio_unit_plugindir = "~/Library/Audio/Plug-Ins/Components"; # Target location for Audio Unit Plugins.
      vst_plugindir = "~/Library/Audio/Plug-Ins/VST"; # Target location for VST Plugins.
      vst3_plugindir = "~/Library/Audio/Plug-Ins/VST3"; # Target location for VST3 Plugins.
      screen_saverdir = "~/Library/Screen Savers"; # Target location for Screen Savers.
      require_sha = true; # Whether to require cask(s) to have a checksum.
      no_quarantine = false; # Keep macOS Gatekeeper quarantine enabled for security.
    };

    # Shared casks installed on all machines
    casks =
      [
        # Password management
        # Note: 1password-cli is installed via Nix packages (see common.nix)
        "1password@beta" # Password manager

        # Productivity
        "chatgpt" # OpenAI's official ChatGPT desktop app

        # Browsers
        "ungoogled-chromium" # Google Chromium, sans integration with Google

        # Development
        "gitbutler" # Git client for simultaneous branches on top of your existing workflow
        "visual-studio-code" # Open-source code editor
        "warp" # Rust-based terminal
        "zed@preview" # Multiplayer code editor
        "docker-desktop"
        "microsoft-teams"

        # Utilities
        "pearcleaner" # Utility to uninstall apps and remove leftover files from old/uninstalled apps
        "figma@beta" # Collaborative team software
      ]
      ++ (hostConfig.homebrew.casks or []); # Merge host-specific casks
    /*
    Mac App Store apps managed via Brew Bundle
    Note: You must be signed into the App Store for these installations to succeed.
    To disable: set masApps = {}; or comment out individual apps if not signed in.
    Find app IDs with: mas search "App Name"
    */
    masApps = {
      "1Password for Safari" = 1569813296;
      "Microsoft Outlook" = 985367838;
      "WhatsApp Messenger" = 310633997;
      "Wipr 2" = 1662217862;
      Xcode = 497799835;
    };

    onActivation = {
      autoUpdate = false; # Whether to enable Homebrew to auto-update itself and all formulae during nix-darwin system activation. The default is false so that repeated invocations of darwin-rebuild switch are idempotent.
      /*
      This option manages what happens to formulae installed by Homebrew, that aren't present in the Brewfile generated by this module, during nix-darwin system activation.
      - When set to "none" (the default), formulae not present in the generated Brewfile are left installed.
      - When set to "uninstall", nix-darwin invokes brew bundle [install] with the --cleanup flag. This uninstalls all formulae not listed in generated Brewfile, i.e., brew uninstall is run for those formulae.
      - When set to "zap", nix-darwin invokes brew bundle [install] with the --cleanup --zap flags. This uninstalls all formulae not listed in the generated Brewfile, and if the formula is a cask, removes all files associated with that cask. In other words, brew uninstall --zap is run for all those formulae.
      */
      cleanup = "zap";
      extraFlags = ["--verbose"]; # Extra flags to pass to brew bundle [install] during nix-darwin system activation.
      upgrade = false; # Whether to enable Homebrew to upgrade outdated formulae and Mac App Store apps during nix-darwin system activation. The default is false so that repeated invocations of darwin-rebuild switch are idempotent.
    };

    # Do not set deprecated taps like homebrew/cask-versions or homebrew/cask-fonts;
    # modern Homebrew migrated these into core repos and tapping them now fails.
    taps = [];
  };
}
