echo 'Hello from .zshenv'

# Specify your defaults in this environment variable
export HOMEBREW_CASK_OPTS="--no-quarantine --appdir=/Applications"

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"                                       # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm" # This loads nvm bash_completion

function exists() {
  command -v $1 >/dev/null 2>&1
}
source "$HOME/.cargo/env"
