echo 'Hello from .zshrc'

# Set Variables
# Change ZSH Options

# Create Aliases
alias ls='ls -lAFh'
# alias ls="exa -laFh --git"
# alias exa="exa -laFh --git"
# alias tree="exa --tree --level=2"
# alias man="batman"

# Customize Prompt(s)

# Add Locations to $PATH Variable


# Automatically "Warpify" subshells in "Warp" terminal app
printf '\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "zsh"}}\x9c'

. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
