# eza - A modern replacement for ls
# https://github.com/eza-community/eza
# https://github.com/nix-community/home-manager/blob/master/modules/programs/eza.nix
#
# ══════════════════════════════════════════════════════════════════════════════
# OVERVIEW
# ══════════════════════════════════════════════════════════════════════════════
#
# eza is a modern, maintained replacement for the venerable file-listing
# command-line program ls. It uses colors to distinguish file types and
# metadata, and it understands symlinks, extended attributes, and Git.
#
# Key features:
#   - Colors for file types and permissions
#   - Git integration (shows file status)
#   - Tree view support
#   - Icons support (requires Nerd Font)
#   - Extended attributes and metadata
#   - Hyperlink support for terminal emulators
#
# ══════════════════════════════════════════════════════════════════════════════
# USAGE
# ══════════════════════════════════════════════════════════════════════════════
#
#   eza                        List files in current directory
#   eza -l                     Long format with details
#   eza -la                    Long format including hidden files
#   eza -lah                   Long format, hidden files, human-readable sizes
#   eza -T                     Tree view
#   eza -T -L 2                Tree view, 2 levels deep
#   eza --icons                Show icons (requires Nerd Font)
#   eza --git                  Show git status for each file
#   eza --git-repos            Show git repo status in directory listings
#   eza -s size                Sort by size
#   eza -s modified            Sort by modification time
#   eza -r                     Reverse sort order
#   eza --group-directories-first  List directories before files
#
# ══════════════════════════════════════════════════════════════════════════════
# LONG FORMAT COLUMNS
# ══════════════════════════════════════════════════════════════════════════════
#
# In long format (-l), eza displays:
#
#   Permissions │ Size │ User │ Group │ Date Modified │ Name
#
# With --git:
#   Git Status │ Permissions │ Size │ User │ Group │ Date Modified │ Name
#
# Git status indicators:
#   - (dash)    Unmodified       N  New file
#   M           Modified         D  Deleted
#   I           Ignored          R  Renamed
#   U           Updated          T  Type change
#
# ══════════════════════════════════════════════════════════════════════════════
# SHELL ALIASES (auto-generated by home-manager)
# ══════════════════════════════════════════════════════════════════════════════
#
# When shell integration is enabled, these aliases are created:
#
#   ls   → eza
#   ll   → eza -l
#   la   → eza -a
#   lt   → eza --tree
#   lla  → eza -la
#
# Additional custom aliases are defined in shell configs (zsh.nix, fish/)
#
# ══════════════════════════════════════════════════════════════════════════════
# INTEGRATION
# ══════════════════════════════════════════════════════════════════════════════
#
# eza is used throughout this configuration:
#   - fzf ⌥C (Option-C) preview: directory tree view
#   - zoxide cdi preview: directory tree view
#   - fcd fish function: directory preview
#   - Custom shell aliases for enhanced ls experience
#
{
  lib,
  pkgs,
  ...
}: let
  inherit (lib) mkDefault;
in {
  programs.eza = {
    enable = true;
    package = mkDefault pkgs.eza;

    # ────────────────────────────────────────────────────────────────────────
    # Icons
    # ────────────────────────────────────────────────────────────────────────
    # Display icons next to file names. Requires a Nerd Font.
    # Options: "auto" (detect TTY), "always", "never", or null (disabled)
    icons = mkDefault "auto";

    # ────────────────────────────────────────────────────────────────────────
    # Git Integration
    # ────────────────────────────────────────────────────────────────────────
    # Show Git status for tracked/ignored files in long view.
    # Adds a column showing staged/unstaged status.
    git = mkDefault true;

    # ────────────────────────────────────────────────────────────────────────
    # Colors
    # ────────────────────────────────────────────────────────────────────────
    # When to use terminal colors. Options: "auto", "always", "never"
    colors = mkDefault "auto";

    # ────────────────────────────────────────────────────────────────────────
    # Extra Options
    # ────────────────────────────────────────────────────────────────────────
    # Additional flags passed to eza by default (via shell alias)
    extraOptions = [
      "--group-directories-first" # Directories before files
      "--header" # Show column headers in long view
      "--group" # Show group in long view
    ];

    # ────────────────────────────────────────────────────────────────────────
    # Shell Integrations
    # ────────────────────────────────────────────────────────────────────────
    # Automatically enabled by home-manager based on which shells are active.
    # Creates aliases: ls, ll, la, lt, lla
    # See: lib.hm.shell.mk*IntegrationOption in home-manager source

    # ────────────────────────────────────────────────────────────────────────
    # Custom Theme
    # ────────────────────────────────────────────────────────────────────────
    # Written to ~/.config/eza/theme.yml
    # See: https://github.com/eza-community/eza/blob/main/man/eza_colors-explanation.5.md
    #
    # Uncomment to customize colors:
    # theme = {
    #   # File types
    #   filenames = {
    #     "Makefile" = { foreground = "green"; };
    #     "Cargo.toml" = { foreground = "red"; };
    #   };
    #   # Extensions
    #   extensions = {
    #     "rs" = { foreground = "red"; };
    #     "nix" = { foreground = "blue"; };
    #   };
    # };
    theme = {};
  };
}
