#! /usr/bin/env bash

eval "$(starship init bash)"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
source "$HOME/.cargo/env"
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

PATH=~/.console-ninja/.bin:$PATH