#! /usr/bin/env bash

eval "$(starship init bash)"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
source "$HOME/.cargo/env"

PATH=~/.console-ninja/.bin:$PATH

# Automatically "Warpify" subshells in "Warp" terminal app
printf '\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "bash"}}\x9c'
